language: python
matrix:
  include:
  # Python 3.5 with ghdl llvm
  - env: BUILD_NAME=py35-acceptance-ghdl
    python: '3.5'
    os: linux
    sudo: required
    dist: trusty
    before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y gnat-4.8 zlib1g-dev
    - sudo apt-get install -y llvm-3.5-dev llvm-3.5-tools libedit-dev
    - sudo apt-get install -y caca-utils
    before_script:
    - git clone --depth 1 https://github.com/tgingold/ghdl.git ghdl
    - cd ghdl
    - mkdir build-llvm
    - cd build-llvm
    - ../configure --prefix=../../install-ghdl-llvm/ --with-llvm-config=llvm-config-3.5
    - make
    - make install
    - cd ../../
    - export PATH=$PATH:install-ghdl-llvm/bin/
    - git clone --recursive https://github.com/VUnit/vunit.git
    - cd vunit
    - python setup.py install
    - cd ..

addons:
  apt:
    packages:
      - oracle-java8-installer

install:
  - pip install opencv-python
  - pip install imutils

script:
- bash tests.sh 

notifications:
  email: false
  slack: elementosdesistemas:ofJV6uLFlgvMBAR0YDOgeGwl#github_privado
